import "@/app/_styles/globals.css";
import Navbar from "./_components/Navbar";
// import "./_styles/globals.css";

export const metadata = {
  title: "Data Science Club",
  // description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="">
        <Navbar />
        <main>{children}</main>
      </body>
    </html>
  );
}
